AllCops:
  Include:
    - Rakefile
  Exclude:
    - bin/**
    - Gemfile
Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/AbcSize:
  Max: 25
Metrics/BlockLength:
  Exclude:
    - 'Gemfile'
    - 'Rakefile'
    - 'spec/**/*.rb'
Metrics/LineLength:
  Max: 130
  Exclude:
    - 'Gemfile'
    - 'Rakefile'
    - 'spec/**/*.rb'
Metrics/MethodLength:
  Max: 120
  Exclude:
    - 'Gemfile'
    - 'Rakefile'
    - 'spec/**/*.rb'



